### ISSUE TITLE
Reorganize content on site

### ISSUE THREAD

**Issue by peplin** [openxc/openxcplatform.com#10]
Three top-level categories
## Basics
- Overview (the current "Getting Started" page)
- Vehicle Data
- Android Library Setup
- "Hello Car" Tutorial
## Mobile
- Supported Devices
- Android API Guide
- Testing
## In-Vehicle
- Vehicle Interface
  - chipKIT Assembly
- Testing
  - Utilities
- Supported Vehicles

Minor categories:
## Reference
- Android Library
  - Source
  - Docs
- Vehicle Interface
  - Source
  - Docs
- Python Library
  - Source
  - Docs
## Grab-bag category

May or may not have a top-level category of its own.
- About the Project (current "Overview" page, should be reworked to be good for non-technical media)
- FAQ
- Contributing
- Projects

**Comment by peplin** [comment]
@jrod-001 starting from your wireframes, this is a starting point for organizing things.

**Comment by jrod-001** [comment]
@peplin flow chart now in sandbox branch

**Comment by jrod-001** [comment]
flow chart now here
![current structure](https://f.cloud.github.com/assets/751694/614129/a6238520-ce15-11e2-85e5-b52a93eb61db.png)
![proposed structure](https://f.cloud.github.com/assets/751694/614130/a63c8ab6-ce15-11e2-9102-956b8dd2f325.png)
![proposed structure 2](https://f.cloud.github.com/assets/751694/614132/a650b22a-ce15-11e2-8ae6-b6b193bd6d03.png)
![proposed structure 3](https://f.cloud.github.com/assets/751694/614131/a64fd58a-ce15-11e2-9010-dfeeba882443.png)

**Comment by peplin** [comment]
The proposed structure looks good to me.

**Comment by peplin** [comment]
The graphic in [this PDF](https://owncloud.fordsvl.com/public.php?service=files&t=9666b7be5fd63e42a24e83f90352bd9e&download) may be a good candidate to have on the front page as a high level overview of the platform.

**Comment by mjohn706** [comment]
Overall, I like the diagram, bu the label in gray, "Micro USB" seems to refer to the unused connector, not the the connector represented by the blue curve from the VI to the unnamed device in the lower right.

So these are the changes I would make before putting this out there front page: 1) label the blue curve 2) label the device in the lower right. 3) why label Micro USB if we are not using it? Best solution would be to show what it is for. 4) "Diagnostic Port" is really the OBD II required to be in reach of the driver, not just ANY diagnostic port, like the diagnostic port that is still common under the hood.

On Aug 28, 2013, at 4:58 PM, Christopher Peplin <notifications@github.com<mailto:notifications@github.com>> wrote:

The graphic in this PDFhttps://owncloud.fordsvl.com/public.php?service=files&t=9666b7be5fd63e42a24e83f90352bd9e&download may be a good candidate to have on the front page as a high level overview of the platform.
