### ISSUE TITLE
Error in cygwin dependencies of the CAN Translator Installation documentation

### ISSUE THREAD

**Issue by jkristin** [openxc/openxcplatform.com#14]
The instructions on the /cantranslator/installation/installation.html has error in the required Cygwin packages:

python-argparse - not available through latest Cygwin in Windows. Doesn't seeem to be needed
ncurses - not mentioned. Needed
make - not mentioned. Needed

The "Installation" instructions are also different from the "Flash a precombined binary"
[1] = http://openxcplatform.com/cantranslator/installation/installation.html
[2] = http://openxcplatform.com/cantranslator/installation/binary.html
(comments above is for #1)

Both of them are referred to as the "CAN translator documentation" on the page "CAN Translator Firmware" (/vehicle-interface/firmware.html)

**Comment by peplin** [comment]
Thanks for the report, Johannes. There are two different sets of instructions because to just flash a pre-compiled binary, you don't need as many dependencies. The bootstrap script for the full compile installation should catch if make and ncurses are missing - did you get an error, or were you just walking through the dependencies manually?

**Comment by jkristin** [comment]
Oh, I must have clicked the second link to the "CAN translator document" as I added the cygwin packages described in [2].
The two dependency issues I had was both errors from running the script/upload_hex.sh. The first time the script aborted for "ncurses" not installed, I cygwin added it, and then the second time the script aborted since "make" was not instsalled. I cygwin added that and everything worked.
As I probably installed more packages than necessary for just flashing, I do not know exactly the list of cygwin packages that need to be installed, but at least "ncurses" and "make" needs to be added as the flash script will fail otherwise.

Also, I would suggest that we rename the links on the openxcplatform.com/vehicle-interface/firmware.html page so that they are not both called "CAN translator documentation" as they lead to two different pages.

**Comment by peplin** [comment]
The installation docs have been updated (a while ago, just cleaning up tickets).
