### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by n3ls0n** [openxc/openxcplatform.com#23]
There's a broken link in your index.html line 89.  Broken URL: https://media.ford.com/article_display.cfm?article_id=38054

The link seems important as according to the copy should pull-up a list of upcoming workshops.

Cheers.

**Comment by peplin** [comment]
Thanks, looks like media.ford.com decided to change all of their URLs - looks like they haven't heard the news that [cool URLs don't change](http://www.w3.org/Provider/Style/URI.html).
