### ISSUE TITLE
Add Search bar to right end of top nav bar

### ISSUE THREAD

**Issue by jkitch20** [openxc/openxcplatform.com#30]
Adding a search bar to search through the site could be really helpful, especially for developers who've gone through the site but remembered some bit of text they'd like to revisit. 
It could even possibly be set up to search over each of the subsites (VI, Python, etc) to help search through the code documentation.

Anyone have any thoughts or objections?

**Comment by peplin** [comment]
Let's table this until after the redesign - if we can't manage to whip the site into better organizational shape, we'll re-open this issue.
