### ISSUE TITLE
Consolidate layout

### ISSUE THREAD

**Issue by sudo-a13** [openxc/openxcplatform.com#39]
for the page- http://openxcplatform.com/hardware.html

Clicking the top menu bar "Hardware" lands to a page called " Supported Hardware" with three links "supported VIs", "host devices" and "compatible vehicle". 

These options are redundant with the left menu bar which has the same heading "Supported Hardware" and 3/4 options are the same as the main page, except "Android Devices".

Given that the main page now has "see the hardware" which takes them to the "supported VI page". I think one of them can be removed.

**Comment by peplin** [comment]
"Hardware" is the top level category - the 4 pages underneath that section all have the same sidebar so you can navigate between the sub-sections. What would you prefer to display when you click "Hardware" at the top of the page? It could have more general content, but someone would have to create that.

**Comment by sudo-a13** [comment]
I think the 4 page sidebar makes sense. But when you click on the 3 big links (blue boxes) they have similar function to the sidebar.  I like the idea of a general content, with the sidebar working more like a content index. 

So for this page (http://openxcplatform.com/android/getting-started.html), the left sidebar serves as a content page, so you literally step through each page, as the end of each page is "NEXT STEPS". An example where it works

**Comment by peplin** [comment]
The difference I see is that the Android getting started section's top level page has a link in the sidebar as well - when you click "Developers" across the top of the page this is where you land. In "Hardware" section we could very easily add an active link on the left when you're at the top-level of "Hardware" but that doesn't seem to get at the root of what you have an issue with, does it?
