### ISSUE TITLE
Change name of the "contributors" folder

### ISSUE THREAD

**Issue by nathorne** [openxc/openxcplatform.com#50]
@tgiuli noticed the following issue:

If I clone a fresh copy of the openxcplatform.com repo, git status returns:
# Changes not staged for commit:
#    (use "git add/rm <file>..." to update what will be committed)
#    (use "git checkout -- <file>..." to discard changes in working directory)
# 
#        deleted:    CONTRIBUTORS
# 

After some research, I believe this is due to having a "CONTRIBUTORS" file and a "contributors" directory in the same folder in the repo. When doing a clone, the "contributors" file is pulled down, then when the "contributors" directory is pulled down, the new local git repo recognizes this as a change to the "CONTRIBUTORS" file.

**Comment by peplin** [comment]
damn case insensitive filesystems :) fixed in 2307b8a6d0
