### ISSUE TITLE
Post external projects that use OpenXC

### ISSUE THREAD

**Issue by devan224** [openxc/openxcplatform.com#6]
Do people think that it is necessary to distinguish between software and hardware projects? I think it would be nice to just have a list of projects, maybe with some visual images, in the Projects using OpenXC. I think that we are beginning to see that there is not a clear distinction between the two and so maybe it is best to have just a project page.

**On a side note, we should ask if Gracenote wants to add their project to our page. It would be nice to have an outside project here :)

**Comment by peplin** [comment]
Agreed, already working on this in backup-camera branch.

**Comment by tgiuli** [comment]
Yup, I'll check with Gracenote to see if they have a project page we can link to.  For external projects, I'm thinking it's best for us to have a summary page with a link to the main page.  I'll also ping HCL and see if there's a project page they'd like us to link to as well.
